### ISSUE TITLE
windows stdcall

### ISSUE THREAD

**Issue by mnar53** [OpenMathLib/OpenBLAS#423]
the windows dll is compiled with the cdecl convention. As i'm linking openblas into excel, and VBA understands only stdcall convention, i'm forced to create an interface stcall dll (at this moment, in visual fortran) just to pass the call parameters to the cdecl routine. 
 As you can imagine, given the number of routines this is a very long and error prone procedure (i'm doing it manually).

So, the issue is: is it possible to have the windows binary compiled with stdcall, as the unique one or as an alternative to current one?

**Comment by martin-frbg** [comment]
Seeing that this issue is now over ten years old, 32bit Windows has become the exception rather than the norm IMHO, building from source has gotten a lot simpler in the meantime, and (at least according to my limited understanding) it would be sufficient to use `/Gz` in the compiler flags to get a build that both uses and assumes `stdcall` by default for any unqualified interface, I'm going to close this.
(I notice libgit2 had a similar proposal rejected around the same time, https://github.com/libgit2/libgit2/pull/749 from which a patch could be derived if need be, and dropped all support for stdcall sometime in 2019)
