### ISSUE TITLE
Row Major and Col Major problem in gemv_n.c

### ISSUE THREAD

**Issue by AjaySingh40** [OpenMathLib/OpenBLAS#4779]
Hello All,
   I tried writing SVE code for gemv_n.S and integrated in openblas. I wrote sve code in Row Major Order. The problem i am facing is it does not give the expected output in Col Major Order. Do i need to make any modification for it to run for both Row Major and Col Major Order.
Thank You.

**Comment by martin-frbg** [comment]
BLAS is column-major by convention (stemming from the reference implementation having been written in Fortran), the optional transposition is usually handled in the CBLAS interface. But if you check interface/gemv.c you will notice that OpenBLAS has separate GEMV kernels for the n(otranspose) and t(ranspose) case, so probably you have accidentally written the (equally useful) gemv_t kernel instead of gemv_n
